"""star_algebra.py
Article_001 — build the associative *-algebra A_R^(M) generated by the
partial-translation matrices {T_t : t in Delta_M(Sigma_R)}, and its
self-adjoint part J = A_sa with the Jordan product (1/2)(AB+BA).

We work with sparse 0/1 (and rational) matrices via the dict representation
defined in linalg.py.  An IndependentSpan is grown by iteratively multiplying
existing basis elements by the generators on the left and on the right, until
no new linearly independent matrix is produced.

The output of build_associative_star_algebra is:
    n           — dimension of the underlying l^2 (number of patch points)
    gens        — dict { t -> T_t } of generators (sparse Mat)
    basis_A     — list of sparse matrices forming a vector-space basis of A
    span_A      — the IndependentSpan that produced basis_A

The output of build_jordan_subalgebra is:
    basis_J     — list of self-adjoint sparse matrices forming a basis of J
    span_J      — IndependentSpan for J (used later to express products)

All matrices are over Q.

Version: 1
"""
from typing import Dict, List, Tuple
from linalg import (
    Mat, mat_to_svec, svec_to_mat, mat_eq, mat_add, mat_scalar, mat_mul,
    mat_transpose, IndependentSpan, HALF, ONE,
)


def build_associative_star_algebra(generators: Dict[Tuple[int, int], Mat], n: int,
                                   track_transformation: bool = False):
    """Iteratively close generators under matrix multiplication.
    Returns (basis_mats, span). The *-closure is automatic because generators
    already contain T_t and T_{-t}, and matrix * involves only transposition,
    which here equals T_{-t} for partial translations.
    Set track_transformation=True only if you later need span.coords() — much slower.
    """
    span = IndependentSpan(track_transformation=track_transformation)
    basis_mats: List[Mat] = []
    for t, T in generators.items():
        v = mat_to_svec(T, n)
        if span.append_if_new(v):
            basis_mats.append(dict(T))

    gens_list = list(generators.values())
    frontier = list(basis_mats)
    while frontier:
        new_added: List[Mat] = []
        for A in frontier:
            for g in gens_list:
                for P in (mat_mul(A, g), mat_mul(g, A)):
                    if not P:
                        continue
                    v = mat_to_svec(P, n)
                    if span.append_if_new(v):
                        basis_mats.append(P)
                        new_added.append(P)
        frontier = new_added
    return basis_mats, span


def build_jordan_subalgebra(basis_A: List[Mat], n: int):
    """Form the symmetric projection sym(M) = (M + M^T)/2 for every basis
    element of A and gather a linearly independent set as a basis of J = A_sa.
    """
    span_J = IndependentSpan()
    basis_J: List[Mat] = []
    for M in basis_A:
        Mt = mat_transpose(M)
        S = mat_scalar(HALF, mat_add(M, Mt))
        if not S:
            continue
        v = mat_to_svec(S, n)
        if span_J.append_if_new(v):
            basis_J.append(S)
    return basis_J, span_J


def express_in_basis(span_X: IndependentSpan, M: Mat, n: int):
    """Return tuple of Fractions of length len(span_X.basis) expressing M in
    span_X.basis. Raises if M not in span."""
    v = mat_to_svec(M, n)
    return span_X.coords(v)
